---
#
# Ansible managed
#
repository:
  description: Configure Name Server Switch on your systems.
  homepage: https://buluma.github.io/
  topics: nsswitch, ansible, molecule, tox, playbook, hacktoberfest
