---
#
# Ansible managed
#

name: Ansible Molecule

on:
  push:
    branches:
      - master
      - main
      - testing
    paths-ignore:
      - '**/README.md'
      - '**/CHANGELOG.md'
    tags_ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '27 14 14 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  og_lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: buluma/molecule-action@v4.0.8
        with:
          command: lint

  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: ansible-lint
        uses: ansible/ansible-lint@v6.22.1
  test:
    needs:
      - lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "fedora-systemd"
            tag: "38"
          - image: "fedora-systemd"
            tag: "latest"
          - image: "fedora-systemd"
            tag: "rawhide"
          - image: "enterpriselinux"
            tag: "7"
          - image: "enterpriselinux"
            tag: "8"
          - image: "enterpriselinux"
            tag: "latest"
    steps:
      - name: Checkout Role
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - name: Running Molecule Test
        uses: buluma/molecule-action@v6.0.0
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
